### ISSUE TITLE
Setup credentials for CI release

### ISSUE THREAD

**Issue by armanbilge** [djspiewak/cats-effect-testing#274]
The snapshot publish job failed because there are currently no sonatype credentials installed as secrets on this repo.

```
  env:
    PGP_PASSPHRASE: 
    SONATYPE_PASSWORD: 
    SONATYPE_USERNAME: 
    PGP_SECRET: ***
    GITHUB_TOKEN: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.312-7/x64
```

https://github.com/typelevel/cats-effect-testing/runs/5107888927

Linking to https://github.com/typelevel/governance/issues/23 which will fix this.
